export const QUEUE_STAGE = {
  REGISTRATION: 'REGISTRATION',
  BLOOD_COLLECTION: 'BLOOD_COLLECTION',
  RESULT_PICKUP: 'RESULT_PICKUP',
} as const;

export type QueueStage = (typeof QUEUE_STAGE)[keyof typeof QUEUE_STAGE];

export const QUEUE_STATUS = {
  WAITING: 'WAITING',
  CALLED: 'CALLED',
  SERVING: 'SERVING',
  COMPLETED: 'COMPLETED',
  SKIPPED: 'SKIPPED',
  CANCELLED: 'CANCELLED',
} as const;

export type QueueStatus = (typeof QUEUE_STATUS)[keyof typeof QUEUE_STATUS];

export const QUEUE_EVENT = {
  CREATED: 'CREATED',
  REGISTRATION_CALLED: 'REGISTRATION_CALLED',
  REGISTRATION_RECALLED: 'REGISTRATION_RECALLED',
  REGISTRATION_STARTED: 'REGISTRATION_STARTED',
  REGISTRATION_COMPLETED: 'REGISTRATION_COMPLETED',
  BLOOD_COLLECTION_CALLED: 'BLOOD_COLLECTION_CALLED',
  BLOOD_COLLECTION_RECALLED: 'BLOOD_COLLECTION_RECALLED',
  BLOOD_COLLECTION_STARTED: 'BLOOD_COLLECTION_STARTED',
  BLOOD_COLLECTION_COMPLETED: 'BLOOD_COLLECTION_COMPLETED',
  RESULT_PICKUP_CALLED: 'RESULT_PICKUP_CALLED',
  RESULT_PICKUP_RECALLED: 'RESULT_PICKUP_RECALLED',
  RESULT_PICKUP_STARTED: 'RESULT_PICKUP_STARTED',
  RESULT_PICKUP_COMPLETED: 'RESULT_PICKUP_COMPLETED',
  AUTO_CALLED: 'AUTO_CALLED',
  SKIPPED: 'SKIPPED',
  CANCELLED: 'CANCELLED',
} as const;

export type QueueEventType = (typeof QUEUE_EVENT)[keyof typeof QUEUE_EVENT];
